name: benchmark

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  benchmark:
    name: Run benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build and install tascli
        run: cargo install --path .

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bc
          sudo apt-get install -y zsh
          cargo install hyperfine

      - name: Run benchmarks
        shell: zsh
        run: |
          ./bench/github_workflow.sh
